name: Build, Sign, and Push Docker Image (for develop only)

on:
  push:
    branches:
      - develop

env:
  REGISTRY: docker.io
  IMAGE_NAME: kenzman/provenance

jobs:
  build-sign-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up image tag (develop-SHORT_SHA)
        id: versioning
        run: echo "IMAGE_TAG=develop-${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: |
          docker build -t $REGISTRY/$IMAGE_NAME:$IMAGE_TAG .

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.1.1

      - name: Sign Docker image with Cosign
        env:
          COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
        run: |
          cosign sign --key env://COSIGN_PRIVATE_KEY $REGISTRY/$IMAGE_NAME:$IMAGE_TAG

      - name: Push Docker image to Docker Hub
        run: |
          docker push $REGISTRY/$IMAGE_NAME:$IMAGE_TAG

      - name: Verify Signature with Cosign
        env:
          COSIGN_PUBLIC_KEY: ${{ secrets.COSIGN_PUBLIC_KEY }}
        run: |
          cosign verify --key env://COSIGN_PUBLIC_KEY $REGISTRY/$IMAGE_NAME:$IMAGE_TAG

